# Generated by Django 5.2.1 on 2025-10-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'car_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCarCompatibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_car_compatibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(db_column='image', upload_to='products/')),
            ],
            options={
                'db_table': 'product_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductYear',
            fields=[
                ('year_id', models.AutoField(db_column='year_id', primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_column='year')),
            ],
            options={
                'db_table': 'product_years',
                'managed': False,
            },
        ),
    ]
