# Generated by Django 5.2.1 on 2025-10-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_carmodel_productcarcompatibility_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(db_column='address_id', primary_key=True, serialize=False)),
                ('street_house_building_no', models.CharField(db_column='street_house_building_no', max_length=255)),
                ('is_default', models.BooleanField(db_column='is_default', default=False)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('barangay_id', models.AutoField(db_column='barangay_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'barangay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.AutoField(db_column='courier_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'courier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(db_column='delivery_id', primary_key=True, serialize=False)),
                ('delivery_fee', models.IntegerField(db_column='delivery_fee', default=0)),
                ('overall_total', models.IntegerField(db_column='overall_total', default=0)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('tracking_number', models.CharField(blank=True, db_column='tracking_number', max_length=255, null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('status_id', models.AutoField(db_column='status_id', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='status_name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('sequence_order', models.IntegerField(db_column='sequence_order', default=0)),
            ],
            options={
                'db_table': 'delivery_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModePayment',
            fields=[
                ('payment_id', models.AutoField(db_column='payment_id', primary_key=True, serialize=False)),
                ('merchant_id', models.IntegerField(blank=True, db_column='merchant_id', null=True)),
                ('ref', models.CharField(blank=True, db_column='ref', max_length=255, null=True)),
            ],
            options={
                'db_table': 'mode_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('municipality_id', models.AutoField(db_column='municipality_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=255, null=True)),
            ],
            options={
                'db_table': 'municipality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(db_column='province_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(db_column='region_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='quantity', default=1)),
                ('price_at_addition', models.IntegerField(db_column='price_at_addition')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'user_cart',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
