# Generated by Django 5.2.1 on 2025-10-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_barangay_courier_delivery_deliverystatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={},
        ),
    ]
